steps:
  # 1. Construir la imagen usando el Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/identidadastral', '.']

  # 2. Subir la imagen al registro de Google
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/identidadastral']

  # 3. Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'identidadastral'
      - '--image'
      - 'gcr.io/$PROJECT_ID/identidadastral'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/identidadastral'
