server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Deshabilitar logs de errores para evitar ruido en Cloud Run
    error_log /dev/stdout info;
    access_log /dev/stdout;
}
